server:
  servlet:
    context-path: /alipay-order-internal
  port: 8093

logging:
  config: classpath:log/logback.xml
mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml

spring:
  profiles:
    active: prod
  jmx:
    enabled: false
aliyun:
  oss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    accessKeyId: LTAIL1idIDliczSS
    accessKeySecret: 8aGzaaC1lyxiNNuxQId2ZldenQFHUf
    bucketName: shanyuanoss
    policy:
      expire: 300
    maxSize: 10
    scaleRatio: 0.50f
    imgPath: https://oss.shanyuankj.com/
    callback: http://localhost:8061/aliyun/oss/callback
    dir:
      prefix: alipay-order/images/internal/

#serveraddr: https://alipayorder.shanyuankj.com/alipay-order-portal
#serveraddr: http://192.168.2.59:8091/alipay-order-portal