spring:
  datasource:
    url: jdbc:mysql://rm-wz9v0y6a7l8z1gr477o.mysql.rds.aliyuncs.com:3336/alipay_order?nullCatalogMeansCurrent=true&useSSL=false&useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=UTF8&allowMultiQueries=true
    username: sykj_common1
    password: sykj@#20191015
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  jpa:
    show-sql: true